// src/components/common/navbar/mobile-sheet/mobile-sheet.tsx
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";
import useUiStore from "@/stores/ui-store";
import { Nav } from "@/types/site";
import { Menu } from "lucide-react";
import NavItem from "./nav-item";

interface MobileSheetProps {
  nav: Nav;
}

const MobileSheet: React.FC<MobileSheetProps> = ({ nav }) => {
  const open = useUiStore((state) => state.openMobileSheet);
  const updateSearchDropdown = useUiStore((state) => state.setMobileSheetOpen);

  return (
    <Sheet open={open} onOpenChange={updateSearchDropdown}>
      <SheetTrigger asChild className="p-0 lg:hidden">
        <Menu size={30} />
      </SheetTrigger>

      <SheetContent className="w-full overflow-auto">
        <ul className="text-primary flex flex-col divide-y">
          {nav.menu.map((props) => (
            <NavItem key={props._key} {...props} />
          ))}
        </ul>
      </SheetContent>
    </Sheet>
  );
};

export default MobileSheet;

// src/components/sheets/mobile-sheet/mobile-sheet.svelte
<script lang="ts">
  import * as Sheet from '$components/ui/sheet/index.js';
  import type { Nav } from '$lib/types/site.types';
  import { Menu } from 'lucide-svelte';
  import NavItem from './nav-item.svelte';
  import { uiStore } from '$lib/stores/ui-store';

  export let nav: Nav;
</script>

<Sheet.Root bind:open={$uiStore.openMobileSheet}>
  <Sheet.Trigger class="p-0 lg:hidden">
    <Menu size={30} />
  </Sheet.Trigger>
  <Sheet.Content class="w-full overflow-auto">
    <ul class="flex flex-col divide-y text-primary">
      {#each nav.menu as navItem}
        <NavItem {navItem} />
      {/each}
    </ul>
  </Sheet.Content>
</Sheet.Root>
