// src/components/common/user-sheet/profile/profile.tsx
import useUserStore from "@/stores/user-store";
import AuthView from "./auth-view/auth-view";
import ProfileView from "./profile-view/profile-view";

interface ProfileProps {}

const Profile: React.FC<ProfileProps> = ({}) => {
  const user = useUserStore((state) => state.user);

  return (
    <div className="space-y-2">{!!user ? <ProfileView /> : <AuthView />}</div>
  );
};

export default Profile;

// src/components/sheets/user-sheet/profile/profile.svelte
<script lang="ts">
  import { userStore } from '$lib/stores/auth-store';
  import AuthView from './auth-view/auth-view.svelte';
  import ProfileView from './profile-view/profile-view.svelte';

  $: ({ user } = $userStore);
</script>

<div class="space-y-2">
  {#if user}
    <ProfileView />
  {:else}
    <AuthView />
  {/if}
</div>
