// src/components/sheets/search-sheet/search-sheet.svelte
<script lang="ts">
  import { Search } from 'lucide-svelte';
  import * as Sheet from '$components/ui/sheet';
  import SearchSheetContent from './search-sheet-content.svelte';
  import { uiStore } from '$lib/stores/ui-store';
</script>

<Sheet.Root bind:open={$uiStore.openSearchSheet}>
  <Sheet.Trigger>
    <div
      class="flex items-center gap-x-2 rounded-full bg-primary/70 px-5 py-2 text-xs text-primary-foreground md:text-sm">
      <Search class="h-[16px] w-[16px] md:h-[18px] md:w-[18px]" />
      <span class="">search</span>
    </div>
  </Sheet.Trigger>
  <Sheet.Content side="top">
    <div class="container">
      <Sheet.Header>
        <Sheet.Title>Yo?</Sheet.Title>
      </Sheet.Header>

      <SearchSheetContent />
    </div>
  </Sheet.Content>
</Sheet.Root>

// src/components/common/navbar/search-sheet/search-sheet.tsx
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet";
import { Search } from "lucide-react";
import SearchSheetContent from "./search-sheet-content";

interface SearchSheetProps {}

const SearchSheet: React.FC<SearchSheetProps> = ({}) => {
  return (
    <Sheet open={true}>
      <SheetTrigger asChild>
        <button className="bg-primary/70 text-primary-foreground flex items-center gap-x-2 rounded-full px-5 py-2 text-xs md:text-sm">
          <Search className="h-[16px] w-[16px] md:h-[18px] md:w-[18px]" />
          <span>search</span>
        </button>
      </SheetTrigger>

      <SheetContent side="top">
        <div className="container">
          <SheetHeader>
            <SheetTitle>Yo?</SheetTitle>
          </SheetHeader>

          <SearchSheetContent />
        </div>
      </SheetContent>
    </Sheet>
  );
};

export default SearchSheet;
