// src/components/sheets/user-sheet/profile/profile-view/profile-view.svelte
<script lang="ts">
  import type { Direction, View } from '$lib/types/common.types';
  import DefaultView from './default-view.svelte';
  import AddDeliveryAddress from './delivery-address/add/add-delivery-address.svelte';
  import EditAddressView from './delivery-address/edit/edit-address-view.svelte';
  import DeliveryAddressView from './delivery-address/delivery-address.svelte';

  let view: View = 'default';
  let direction: Direction = 'left';
</script>

<div>
  {#if view === 'default'}
    <DefaultView bind:view bind:direction />
  {:else if view === 'delivery-addresses'}
    <DeliveryAddressView bind:view bind:direction />
  {:else if view === 'edit-delivery-address'}
    <EditAddressView bind:view bind:direction />
  {:else if view === 'add-delivery-address'}
    <AddDeliveryAddress bind:view bind:direction />
  {/if}
</div>

// src/components/common/user-sheet/profile/profile-view/profile-view.tsx
import { useState } from "react";
import DefaultView from "./default-view";
import DeliveryAddressView from "./delivery-address/delivery-address-view";
import { AnimatePresence } from "framer-motion";
import AddDeliveryAddress from "./delivery-address/add-delivery-address";

interface ProfileViewProps {}

export type View = "default" | "delivery-addresses" | "add-delivery-address";
export type Direction = "left" | "right";

const ProfileView: React.FC<ProfileViewProps> = ({}) => {
  const [view, setView] = useState<View>("default");
  const [direction, setDirection] = useState<Direction>("right");

  return (
    <div>
      <AnimatePresence mode="popLayout">
        {view === "default" ? (
          <DefaultView setView={setView} setDirection={setDirection} />
        ) : view === "delivery-addresses" ? (
          <DeliveryAddressView
            direction={direction}
            setView={setView}
            setDirection={setDirection}
          />
        ) : view === "add-delivery-address" ? (
          <AddDeliveryAddress setView={setView} setDirection={setDirection} />
        ) : null}
      </AnimatePresence>
    </div>
  );
};

export default ProfileView;
