// src/components/common/user-sheet/profile/auth-view/login-form.tsx
import { Button } from "@/components/ui/button";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { loginPostReq } from "@/lib/validators";
import { zodResolver } from "@hookform/resolvers/zod";
import { Eye, EyeOff, RotateCw } from "lucide-react";
import Image from "next/image";
import { useEffect, useState } from "react";
import { UseFormReturn, useForm } from "react-hook-form";
import useFormPersist from "react-hook-form-persist";
import { useSessionStorage } from "usehooks-ts";
import { z } from "zod";
import GoogleIcon from "/public/icons/google.svg";
import FacebookIcon from "/public/icons/facebook.svg";
import { useToast } from "@/components/ui/use-toast";
import { useFormState, useFormStatus } from "react-dom";
import { loginUser } from "@/app/actions/auth-actions";
import Link from "next/link";

interface LoginFormProps {}

type FormProps = z.infer<typeof loginPostReq>;
type FormResponse = { success: boolean | undefined; error?: string };
const formKey = "login-form";
const defaultFormValue = {
  email: "",
  password: "",
};

const LoginForm: React.FC<LoginFormProps> = ({}) => {
  const { toast } = useToast();
  const [value, setValue] = useSessionStorage(formKey, defaultFormValue);
  const [formState, formAction] = useFormState<FormResponse, FormData>(
    loginUser,
    { success: undefined }
  );

  const form = useForm<FormProps>({
    resolver: zodResolver(loginPostReq),
    defaultValues: {
      email: value.email ?? "",
      password: value.password ?? "",
    },
  });

  useFormPersist(formKey, {
    watch: form.watch,
    setValue: form.setValue,
  });

  useEffect(() => {
    if (formState.success === undefined) return;

    if (!formState.success) {
      toast({
        variant: "destructive",
        title: "Uh oh! Something went wrong.",
        description: formState?.error,
      });
    } else {
      form.reset();
      setValue(defaultFormValue);
      toast({
        title: "You've successfully logged in!",
      });
    }
  }, [formState, toast, form, setValue]);

  return (
    <div className="divide-y-2 divide-dashed space-y-3">
      <Form {...form}>
        <form action={formAction} className="space-y-3">
          <FormFields form={form} />
        </form>
      </Form>

      <div className="space-y-3 pt-3">
        <Button
          asChild
          className="bg-[#1877F2] shadow w-full flex justify-center items-center space-x-1.5 hover:bg-[#1877F2]/90"
        >
          <Link
            href={`${process.env.NEXT_PUBLIC_MEDUSA_BACKEND_URL}/store/auth/facebook`}
          >
            <Image
              src={FacebookIcon}
              alt="Facebook Icon"
              width={20}
              height={20}
            />
            <span>Continue With Facebook</span>
          </Link>
        </Button>
        <Button
          asChild
          className="bg-muted hover:bg-muted/90 shadow text-primary w-full flex justify-center items-center space-x-1.5"
        >
          <Link
            href={`${process.env.NEXT_PUBLIC_MEDUSA_BACKEND_URL}/store/auth/google`}
          >
            <Image src={GoogleIcon} alt="Google Icon" width={20} height={20} />
            <span>Continue With Google</span>
          </Link>
        </Button>
      </div>
    </div>
  );
};

export default LoginForm;

const FormFields: React.FC<{
  form: UseFormReturn<FormProps, any, undefined>;
}> = ({ form }) => {
  const { pending } = useFormStatus();
  const [revealPassword, setRevealPassword] = useState(false);

  return (
    <>
      <FormField
        control={form.control}
        name="email"
        render={({ field }) => (
          <FormItem>
            <FormLabel>Email</FormLabel>
            <FormControl>
              <Input {...field} />
            </FormControl>
            <FormMessage />
          </FormItem>
        )}
      />

      <FormField
        control={form.control}
        name="password"
        render={({ field }) => (
          <FormItem>
            <FormLabel>Password</FormLabel>
            <FormControl>
              <div className="relative">
                <Input
                  autoComplete="new-password"
                  type={revealPassword ? "text" : "password"}
                  {...field}
                />
                <button
                  type="button"
                  className="absolute right-5 top-1/2 z-20 -translate-y-1/2"
                  onClick={(e) => {
                    e.stopPropagation();
                    setRevealPassword((prev) => !prev);
                  }}
                >
                  {revealPassword ? <Eye size={18} /> : <EyeOff size={18} />}
                </button>
              </div>
            </FormControl>
            <FormMessage />
          </FormItem>
        )}
      />

      <Button
        disabled={pending || !form.formState.isValid}
        className="mt-2 w-full space-x-1"
      >
        {pending && <RotateCw size={18} className="animate-spin" />}
        <span>Submit</span>
      </Button>
    </>
  );
};

// apps/storefront/src/lib/components/navigation/navbar/user-sheet/profile/login-form.svelte
<script lang="ts">
  import Button from '$lib/components/ui/button/button.svelte';
  import * as Form from '$lib/components/ui/form';
  import Input from '$lib/components/ui/input/input.svelte';
  import { uiStore } from '$lib/stores/ui-store';
  import type { loginPostReq } from '$lib/utils/validators';
  import { Eye, EyeOff, RotateCw } from 'lucide-svelte';
  import type { SuperForm } from 'sveltekit-superforms';
  import type { z } from 'zod';

  export let loginForm: SuperForm<z.infer<typeof loginPostReq>>;
  let reveal = false;

  $: ({ form, enhance, message } = loginForm);
</script>

<form method="POST" action="/auth?/login" use:enhance>
  <Form.Field form={loginForm} name="email">
    <Form.Control let:attrs>
      <Form.Label>Email</Form.Label>
      <Input {...attrs} bind:value={$form.email} />
    </Form.Control>
    <Form.FieldErrors />
  </Form.Field>

  <Form.Field form={loginForm} name="password">
    <Form.Control let:attrs>
      <Form.Label>Password</Form.Label>
      <div class="relative">
        <Input
          {...attrs}
          type={reveal ? 'text' : 'password'}
          bind:value={$form.password} />
        <button
          type="button"
          on:click|stopPropagation={() => (reveal = !reveal)}
          class="absolute right-5 top-1/2 z-20 -translate-y-1/2">
          {#if reveal}
            <Eye size={18} />
          {:else}
            <EyeOff size={18} />
          {/if}
        </button>
      </div>
    </Form.Control>
    <Form.FieldErrors />
  </Form.Field>
  <Form.Button disabled={$uiStore.authLoading} class="mt-2 w-full space-x-1">
    {#if $uiStore.authLoading}
      <RotateCw size={18} class="animate-spin" />
    {/if}
    <span>Submit</span>
  </Form.Button>
</form>

<!-- <Button
  href="http://localhost:9000/store/auth/google/"
  variant="destructive"
  class="">
  <svg
    class="-ml-1 mr-2 h-4 w-4"
    aria-hidden="true"
    focusable="false"
    data-prefix="fab"
    data-icon="google"
    role="img"
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 488 512">
    <path
      fill="currentColor"
      d="M488 261.8C488 403.3 391.1 504 248 504 110.8 504 0 393.2 0 256S110.8 8 248 8c66.8 0 123 24.5 166.3 64.9l-67.5 64.9C258.5 52.6 94.3 116.6 94.3 256c0 86.5 69.1 156.6 153.7 156.6 98.2 0 135-70.4 140.8-106.9H248v-85.3h236.1c2.3 12.7 3.9 24.9 3.9 41.4z">
    </path>
  </svg>
  Sign in with Google
</Button>
<Button
  href="http://localhost:9000/store/auth/facebook"
  class="mb-2 mr-2 inline-flex items-center rounded-lg bg-[#4285F4] px-5 py-2.5 text-center text-sm font-medium text-white hover:bg-[#4285F4]/90 focus:outline-none focus:ring-4 focus:ring-[#4285F4]/50 dark:focus:ring-[#4285F4]/55">
  Sign in with Facebook
</Button> -->
