// src/components/common/user-sheet/profile/profile-view/default-view.tsx
import { MapPin, RotateCw, User2Icon } from "lucide-react";
import { Button } from "@/components/ui/button";
import { signOutUser } from "@/app/actions/auth-actions";
import { useToast } from "@/components/ui/use-toast";
import useUserStore from "@/stores/user-store";
import { User } from "@/types/common";
import { Dispatch, SetStateAction, useState } from "react";
import { View, Direction } from "./profile-view";
import { motion } from "framer-motion";

interface DefaultViewProps {
  setView: Dispatch<SetStateAction<View>>;
  setDirection: Dispatch<SetStateAction<Direction>>;
}

const DefaultView: React.FC<DefaultViewProps> = ({ setView, setDirection }) => {
  const { toast } = useToast();
  const [loading, setLoading] = useState(false);
  const user = useUserStore((state) => state.user) as User;

  async function handleLogout() {
    try {
      setLoading(true);
      await signOutUser();
      toast({
        variant: "default",
        title: "You've successfully logged out!",
      });
    } catch (error: any) {
      toast({
        variant: "destructive",
        title: "Uh oh! Something went wrong.",
        description: error?.toString(),
      });
    } finally {
      setLoading(false);
    }
  }

  return (
    <motion.div
      initial={{ x: -30 }}
      animate={{ x: 0 }}
      exit={{ x: -30 }}
      transition={{}}
    >
      <div className="flex flex-col divide-y">
        <button className="group flex origin-left items-center gap-3 py-3">
          <div className="bg-primary/40 rounded-sm p-1.5">
            <User2Icon size={18} fill="#3A4743" strokeWidth={0} />
          </div>
          <div className="flex flex-col transition-transform duration-300 group-hover:translate-x-0.5">
            <div className=" text-left font-bold">My information</div>
            <div className="text-xs">{user.email}</div>
          </div>
        </button>
        <button
          onClick={() => {
            setDirection("right");
            setView("delivery-addresses");
          }}
          className="group flex items-center gap-3 py-3"
        >
          <div className="bg-primary/40 rounded-sm p-1.5">
            <MapPin size={18} fill="#3A4743" strokeWidth={0} />
          </div>
          <div className="flex flex-col transition-transform duration-300 group-hover:translate-x-0.5">
            <div className=" text-left font-bold">Shipping addresses</div>
          </div>
        </button>
      </div>

      <Button
        disabled={loading}
        onClick={handleLogout}
        className="w-full space-x-1"
      >
        {loading && <RotateCw size={18} className="animate-spin" />}
        <span>Logout</span>
      </Button>
    </motion.div>
  );
};
export default DefaultView;

// src/components/sheets/user-sheet/profile/profile-view/default-view.svelte
<script lang="ts">
  import { invalidateAll } from '$app/navigation';
  import Button from '$components/ui/button/button.svelte';
  import type { Direction, View } from '$lib/types/common.types';
  import { MapPin, RotateCw, User2Icon } from 'lucide-svelte';
  import { toast } from 'svelte-sonner';
  import { fly } from 'svelte/transition';

  export let view: View;
  export let direction: Direction;

  let loading = false;
  const logout = async () => {
    try {
      loading = true;
      await fetch('/auth/logout', {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json',
        },
      });
      invalidateAll();
      toast.success('Logged out successfully');
    } catch (error: any) {
      toast.error(error?.toString());
    } finally {
      loading = false;
    }
  };
</script>

<div in:fly={{ x: -30 }}>
  <div class="flex flex-col divide-y">
    <button class="group flex origin-left items-center gap-3 py-3">
      <div class="rounded-sm bg-primary/40 p-1.5">
        <User2Icon size={18} fill="#3A4743" strokeWidth={0} />
      </div>
      <div
        class="flex flex-col transition-transform duration-300 group-hover:translate-x-1">
        <div class=" text-left font-bold">My information</div>
        <!-- <div class="text-xs">{user.email}</div> -->
      </div>
    </button>
    <button
      on:click={() => {
        direction = 'right';
        view = 'delivery-addresses';
      }}
      class="group flex items-center gap-3 py-3">
      <div class="rounded-sm bg-primary/40 p-1.5">
        <MapPin size={18} fill="#3A4743" strokeWidth={0} />
      </div>
      <div
        class="flex flex-col transition-transform duration-300 group-hover:translate-x-1">
        <div class=" text-left font-bold">Shipping addresses</div>
      </div>
    </button>
  </div>

  <Button disabled={loading} on:click={logout} class="mt-3 w-full space-x-1">
    {#if loading}
      <RotateCw size={18} class="animate-spin" />
    {/if}
    <span>Logout</span>
  </Button>
</div>
