// apps/storefront/src/lib/components/navigation/navbar/user-sidebar/profile/register-form.svelte
<script lang="ts">
  import * as Form from '$lib/components/ui/form';
  import Input from '$lib/components/ui/input/input.svelte';
  import type { signUpReq } from '$lib/utils/validators';
  import { Eye, EyeOff } from 'lucide-svelte';
  import type { SuperForm } from 'sveltekit-superforms';
  import type { z } from 'zod';

  export let signUpForm: SuperForm<z.infer<typeof signUpReq>>;
  let reveal = false;

  $: ({ form, enhance, message } = signUpForm);
</script>

<form method="POST" action="/auth?/signUp" use:enhance>
  <Form.Field form={signUpForm} name="fname">
    <Form.Control let:attrs>
      <Form.Label>First Name</Form.Label>
      <Input {...attrs} bind:value={$form.fname} />
    </Form.Control>
    <Form.FieldErrors />
  </Form.Field>
  <Form.Field form={signUpForm} name="lname">
    <Form.Control let:attrs>
      <Form.Label>Last Name</Form.Label>
      <Input {...attrs} bind:value={$form.lname} />
    </Form.Control>
    <Form.FieldErrors />
  </Form.Field>
  <Form.Field form={signUpForm} name="email">
    <Form.Control let:attrs>
      <Form.Label>Email</Form.Label>
      <Input {...attrs} bind:value={$form.email} />
    </Form.Control>
    <Form.FieldErrors />
  </Form.Field>
  <Form.Field form={signUpForm} name="password">
    <Form.Control let:attrs>
      <Form.Label>Password</Form.Label>
      <div class="relative">
        <Input
          {...attrs}
          type={reveal ? 'text' : 'password'}
          bind:value={$form.password} />
        <button
          type="button"
          on:click|stopPropagation={() => (reveal = !reveal)}
          class="absolute right-5 top-1/2 z-20 -translate-y-1/2">
          {#if reveal}
            <Eye size={18} />
          {:else}
            <EyeOff size={18} />
          {/if}
        </button>
      </div>
    </Form.Control>
    <Form.FieldErrors />
  </Form.Field>
  <Form.Button class="mt-2 w-full">Submit</Form.Button>
</form>

<div class="text-center">
  By signing up, you agree with our <a class="underline" href="/">
    privacy policy
  </a>
  and
  <a class="underline" href="/">terms and service</a>
</div>

// src/components/common/navbar/user-sheet/profile/register-form.tsx
import {
  Form,
  FormField,
  FormItem,
  FormLabel,
  FormControl,
  FormMessage,
} from "@/components/ui/form";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { registerPostReq } from "@/lib/validators";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { useEffect, useState } from "react";
import { Eye, EyeOff } from "lucide-react";

interface RegisterFormProps {}

const RegisterForm: React.FC<RegisterFormProps> = ({}) => {
  const [revealPassword, setRevealPassword] = useState(false);

  const form = useForm<z.infer<typeof registerPostReq>>({
    resolver: zodResolver(registerPostReq),
    defaultValues: {
      email: "",
      firstName: "",
      lastName: "",
      password: "",
      passwordConfirm: "",
      rurl: "",
    },
  });

  function onSubmit(values: z.infer<typeof registerPostReq>) {
    console.log("success", { values });
  }

  return (
    <>
      <Form {...form}>
        <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-3">
          <FormField
            control={form.control}
            name="firstName"
            render={({ field }) => (
              <FormItem>
                <FormLabel>First Name</FormLabel>
                <FormControl>
                  <Input {...field} />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />
          <FormField
            control={form.control}
            name="lastName"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Last Name</FormLabel>
                <FormControl>
                  <Input {...field} />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="email"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Email</FormLabel>
                <FormControl>
                  <Input {...field} />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="password"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Password</FormLabel>
                <FormControl>
                  <div className="relative">
                    <Input
                      autoComplete="new-password"
                      type={revealPassword ? "text" : "password"}
                      {...field}
                    />
                    <button
                      type="button"
                      className="absolute right-5 top-1/2 z-20 -translate-y-1/2"
                      onClick={(e) => {
                        e.stopPropagation();
                        setRevealPassword((prev) => !prev);
                      }}
                    >
                      {revealPassword ? (
                        <Eye size={18} />
                      ) : (
                        <EyeOff size={18} />
                      )}
                    </button>
                  </div>
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="passwordConfirm"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Confirm Password</FormLabel>
                <FormControl>
                  <div className="relative">
                    <Input
                      autoComplete="new-password"
                      type={revealPassword ? "text" : "password"}
                      {...field}
                    />
                    <button
                      type="button"
                      className="absolute right-5 top-1/2 z-20 -translate-y-1/2"
                      onClick={(e) => {
                        e.stopPropagation();
                        setRevealPassword((prev) => !prev);
                      }}
                    >
                      {revealPassword ? (
                        <Eye size={18} />
                      ) : (
                        <EyeOff size={18} />
                      )}
                    </button>
                  </div>
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          <Button className="mt-2 w-full space-x-1">Submit</Button>
        </form>
      </Form>
    </>
  );
};

export default RegisterForm;
