// src/components/sheets/user-sheet/user-sheet.svelte
<script>
  import * as Sheet from '$components/ui/sheet/index';
  import { User2Icon } from 'lucide-svelte';
  import * as Tabs from '$components/ui/tabs';
  import ForYou from './for-you/for-you.svelte';
  import Order from './order/order.svelte';
  import Profile from './profile/profile.svelte';
  import { uiStore } from '$lib/stores/ui-store';
</script>

<Sheet.Root bind:open={$uiStore.openUserSheet}>
  <Sheet.Trigger>
    <User2Icon />
  </Sheet.Trigger>

  <Sheet.Content class="w-full overflow-auto">
    <Sheet.Header>
      <Sheet.Title>Welcome</Sheet.Title>
    </Sheet.Header>

    <Tabs.Root value="profile" class="mt-2 w-full">
      <Tabs.List class="sticky top-0 w-full">
        <Tabs.Trigger value="profile">Profile</Tabs.Trigger>
        <Tabs.Trigger value="order">Orders</Tabs.Trigger>
        <Tabs.Trigger value="for-you">For You</Tabs.Trigger>
      </Tabs.List>

      <Tabs.Content value="profile">
        <Profile />
      </Tabs.Content>
      <Tabs.Content value="order">
        <Order />
      </Tabs.Content>
      <Tabs.Content value="for-you">
        <ForYou />
      </Tabs.Content>
    </Tabs.Root>
  </Sheet.Content>
</Sheet.Root>

// src/components/common/user-sheet/user-sheet.tsx
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet";
import useUiStore from "@/stores/ui-store";
import { User2Icon } from "lucide-react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import Profile from "./profile/profile";
import Order from "./order/order";
import ForYou from "./for-you/for-you";

interface UserSheetProps {}

const UserSheet: React.FC<UserSheetProps> = ({}) => {
  const open = useUiStore((state) => state.openUserSheet);
  const updateSearchDropdown = useUiStore((state) => state.setUserSheetOpen);

  return (
    <Sheet open={open} onOpenChange={updateSearchDropdown}>
      <SheetTrigger asChild>
        <button>
          <User2Icon />
        </button>
      </SheetTrigger>

      <SheetContent className="w-full overflow-auto ">
        <SheetHeader>
          <SheetTitle>Welcome</SheetTitle>
        </SheetHeader>

        <Tabs defaultValue="profile" className="mt-2 w-full ">
          <TabsList className="sticky top-0 w-full">
            <TabsTrigger value="profile">Profile</TabsTrigger>
            <TabsTrigger value="order">Orders</TabsTrigger>
            <TabsTrigger value="for-you">For You</TabsTrigger>
          </TabsList>

          <TabsContent value="profile">
            <Profile />
          </TabsContent>
          <TabsContent value="order">
            <Order />
          </TabsContent>
          <TabsContent value="for-you">
            <ForYou />
          </TabsContent>
        </Tabs>
      </SheetContent>
    </Sheet>
  );
};

export default UserSheet;
