// src/components/common/user-sheet/profile/profile-view/delivery-address/add/add-delivery-address.tsx
import { Dispatch, SetStateAction } from "react";
import { View, Direction } from "../../profile-view";
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { MoveLeft } from "lucide-react";
import Form from "./add-delivery-form";

interface AddDeliveryAddressProps {
  setView: Dispatch<SetStateAction<View>>;
  setDirection: Dispatch<SetStateAction<Direction>>;
}

const AddDeliveryAddress: React.FC<AddDeliveryAddressProps> = ({
  setView,
  setDirection,
}) => {
  return (
    <motion.div initial={{ x: 30 }} animate={{ x: 0 }} exit={{ x: 30 }}>
      <div className="relative py-3 flex justify-end items-center ">
        <Button
          size="sm"
          variant="outline"
          className="group absolute left-0 top-1/2 -translate-y-1/2"
          onClick={() => {
            setView("delivery-addresses");
            setDirection("left");
          }}
        >
          <MoveLeft
            className="group-hover:-translate-x-0.5 transition-transform duration-300"
            size={14}
            stroke="#3A4743"
          />
        </Button>
        <span className="text-xl font-medium underline">Add Address</span>
      </div>

      <Form />
    </motion.div>
  );
};

export default AddDeliveryAddress;

// src/components/sheets/user-sheet/profile/profile-view/delivery-address/add/add-delivery-address.svelte
<script lang="ts">
  import Button from '$components/ui/button/button.svelte';
  import type { Direction, View } from '$lib/types/common.types';
  import { MoveLeft } from 'lucide-svelte';
  import { fly } from 'svelte/transition';
  import Form from './form.svelte';

  export let view: View;
  export let direction: Direction;
</script>

<div in:fly={{ x: 30 }}>
  <div class="relative flex items-center justify-end py-3">
    <Button
      size="sm"
      variant="outline"
      class="group absolute left-0 top-1/2 -translate-y-1/2"
      on:click={() => {
        view = 'delivery-addresses';
        direction = 'left';
      }}>
      <MoveLeft
        class="transition-transform duration-300 group-hover:-translate-x-0.5"
        size={14}
        stroke="#3A4743" />
    </Button>
    <span class="text-xl font-medium underline">Add Addresses</span>
  </div>

  <Form />
</div>
